name: atv_flutter_03
description: Conversor de Moedas

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"
  flutter_app_name: ^0.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_app_name:
  name: "Conversor de Moedas"
